import { z } from "zod";

/**
 * Brief structuré produit par l'agent à la fin de l'étape 2.
 *
 * Architecture en deux axes de variation :
 *   - angles[]   : variations de COPY (différents angles marketing pour le même produit)
 *   - concepts[] : variations de VISUEL (différents traitements créatifs : 3D, photo, dessin…)
 *
 * À la génération, l'utilisateur choisit M angles × N concepts × K modèles → M·N·K images.
 */

/**
 * A copy variant for an angle — alternate headline/body/cta exploring the
 * SAME angle from a different angle (pun intended). Generated on demand by
 * the user clicking "Générer N variantes" on a brief angle.
 */
export const copyVariantSchema = z.object({
  id: z.string(), // local uuid
  headline: z.string(),
  body: z.string().optional(),
  cta: z.string().optional(),
  emphasis_words: z.array(z.string()).optional(),
});

export type CopyVariant = z.infer<typeof copyVariantSchema>;

export const angleSchema = z.object({
  name: z
    .string()
    .describe("Nom court de l'angle marketing (3-5 mots, ex: 'Sécurité absolue')"),
  rationale: z
    .string()
    .describe("Pourquoi cet angle peut convertir (1 phrase)"),
  headline: z.string().describe("Hook principal — court, percutant, max 8 mots"),
  body: z.string().optional().describe("Argument court — 1 phrase max"),
  cta: z.string().optional().describe("Call-to-action — 2-4 mots, impératif"),
  emphasis_words: z
    .array(z.string())
    .optional()
    .describe("Mots du headline à mettre en accent (max 3)"),
  // copy_variants are NOT generated by Claude on finalize — they're added by
  // the user via the "Générer N variantes" button on the brief page. Optional
  // so old briefs and Claude-finalized briefs validate normally.
  copy_variants: z.array(copyVariantSchema).optional(),
});

/**
 * Style de rendu d'un concept visuel — détermine l'esthétique globale et le
 * "ton" du créa. Mixer ces styles à travers les concepts d'un brief permet de
 * tester des registres très différents (premium vs UGC vs éditorial vs meme),
 * ce qui est crucial sur Meta où l'ad-blindness pénalise le tout-cinematic.
 */
export const renderStyleSchema = z.enum([
  "cinematic", // Apple keynote, Octane render, premium polished (default)
  "ugc", // Phone-shot, natural light, casual — looks like a real person filmed it
  "screenshot_social", // Faux SMS / DM / tweet / Instagram comment screenshot
  "editorial", // Magazine finance (Les Echos, Capital, Investir) — serif headline
  "comparison_split", // Diptyque before/after, vs concurrence, statu-quo / solution
  "data_viz", // Chart-driven infographic — la data est le héros
  "meme", // Format meme (Drake, Two Buttons…) avec punchline
]);

export type RenderStyle = z.infer<typeof renderStyleSchema>;

export const RENDER_STYLE_LABELS: Record<RenderStyle, string> = {
  cinematic: "Cinematic premium",
  ugc: "UGC / phone-shot",
  screenshot_social: "Screenshot social",
  editorial: "Éditorial finance",
  comparison_split: "Comparaison split",
  data_viz: "Data viz / infographic",
  meme: "Meme",
};

/**
 * Une variante visuelle d'un concept — même thème, traitement différent.
 * Ex : si le concept est "triangle de sécurité", les variantes peuvent être
 * un coffre-fort, un cadenas, une voûte, etc. Toutes illustrent la sécurité
 * mais avec des visuels distincts. Générées à la demande par l'utilisateur
 * via le bouton "Générer N variantes" sur la carte d'un concept.
 */
export const conceptVariantSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  render_style: renderStyleSchema.optional(),
});

export type ConceptVariant = z.infer<typeof conceptVariantSchema>;

export const conceptSchema = z.object({
  name: z
    .string()
    .describe("Nom court du concept visuel (3-5 mots, ex: 'Triangle 3D obsidian')"),
  rationale: z
    .string()
    .describe("Pourquoi ce concept fait sens (1 phrase)"),
  render_style: renderStyleSchema
    .optional()
    .describe(
      "Style de rendu : cinematic / ugc / screenshot_social / editorial / comparison_split / data_viz / meme. Doit être cohérent avec la description. Default : cinematic."
    ),
  description: z
    .string()
    .describe(
      "Description visuelle EN du concept (200+ mots, dense, prête à injecter dans un prompt d'image). Inclut matières, lumière, palette, profondeur, références. PAS de texte intégré ici — le copy sera ajouté au moment de la génération. Si render_style ≠ cinematic, la description doit refléter ce style (ex: pour ugc, décrire la scène phone-shot avec lumière naturelle, sujet humain ; pour screenshot_social, décrire l'UI et le contenu textuel ; pour editorial, le layout magazine ; etc.)."
    ),
  // concept_variants are NOT generated by Claude on finalize — added by the
  // user via "Générer N variantes" or "Modifier avec mon idée" buttons.
  concept_variants: z.array(conceptVariantSchema).optional(),
  // For render_style="comparison_split" : the two short labels (UPPERCASE,
  // 1-3 words) to render at the top of each half. e.g. ["AVANT", "APRÈS"],
  // ["VOTRE BANQUE", "[PRODUIT]"], ["SANS X", "AVEC X"]. Required only for
  // comparison_split — Claude fills it when it picks that render_style.
  comparison_labels: z
    .array(z.string())
    .length(2)
    .optional()
    .describe(
      "Pour render_style=comparison_split UNIQUEMENT : les deux labels courts (1-3 mots, MAJUSCULES) du diptyque. Ex : ['AVANT','APRÈS'], ['VOTRE BANQUE','NOTRE OFFRE']."
    ),
});

export const briefSchema = z.object({
  product_summary: z
    .string()
    .describe("Synthèse en 1-2 phrases du produit / offre / cible"),

  art_direction: z.object({
    overall_mood: z.string(),
    palette: z.array(z.string()),
    typography: z.string().optional(),
  }),

  text_overlay: z.object({
    // Layouts disponibles :
    //  - bottom / top / center / split-bottom : classiques (bloc horizontal)
    //  - side-strip-left / side-strip-right    : barre verticale 35%
    //  - sticker-burst                          : sticker rond rotaté coin
    //  - magazine-cover                         : kicker + serif huge headline
    //  - floating-card                          : carte centrée glass-effect
    //  - marquee-band                           : bandeau horizontal centré
    //  - corner-tag                             : ruban diagonal coin + tag
    // Le brief sert de DÉFAUT — au moment de la génération, les images sont
    // distribuées sur l'ensemble du palette pour varier les compositions.
    layout: z.enum([
      "bottom",
      "top",
      "center",
      "split-bottom",
      "side-strip-left",
      "side-strip-right",
      "sticker-burst",
      "magazine-cover",
      "floating-card",
      "marquee-band",
      "corner-tag",
      "comparison-bottom",
    ]),
    theme: z.object({
      text_color: z.string(),
      accent_color: z.string(),
      accent_text_color: z.string(),
      scrim: z.enum(["none", "bottom-fade", "top-fade", "full-dark", "full-light"]),
    }),
  }),

  angles: z.array(angleSchema).min(2).max(6),
  concepts: z.array(conceptSchema).min(2).max(6),
});

export type Angle = z.infer<typeof angleSchema>;
export type Concept = z.infer<typeof conceptSchema>;
export type Brief = z.infer<typeof briefSchema>;

export const briefToolJsonSchema = {
  type: "object",
  properties: {
    product_summary: { type: "string" },
    art_direction: {
      type: "object",
      properties: {
        overall_mood: { type: "string" },
        palette: { type: "array", items: { type: "string" } },
        typography: { type: "string" },
      },
      required: ["overall_mood", "palette"],
    },
    text_overlay: {
      type: "object",
      properties: {
        layout: {
          type: "string",
          enum: [
            "bottom",
            "top",
            "center",
            "split-bottom",
            "side-strip-left",
            "side-strip-right",
            "sticker-burst",
            "magazine-cover",
            "floating-card",
            "marquee-band",
            "corner-tag",
            "comparison-bottom",
          ],
        },
        theme: {
          type: "object",
          properties: {
            text_color: { type: "string" },
            accent_color: { type: "string" },
            accent_text_color: { type: "string" },
            scrim: {
              type: "string",
              enum: ["none", "bottom-fade", "top-fade", "full-dark", "full-light"],
            },
          },
          required: ["text_color", "accent_color", "accent_text_color", "scrim"],
        },
      },
      required: ["layout", "theme"],
    },
    angles: {
      type: "array",
      minItems: 2,
      maxItems: 6,
      description:
        "Variations de COPY — chaque angle est un autre angle marketing pour le même produit (urgence, social proof, performance, peur de manquer, statut, etc.). Diversifiez les leviers psychologiques.",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          rationale: { type: "string" },
          headline: { type: "string" },
          body: { type: "string" },
          cta: { type: "string" },
          emphasis_words: { type: "array", items: { type: "string" } },
        },
        required: ["name", "rationale", "headline"],
      },
    },
    concepts: {
      type: "array",
      minItems: 2,
      maxItems: 6,
      description:
        "Variations de VISUEL — chaque concept est un traitement créatif différent. CRUCIAL : MIXER LES render_style (cinematic / ugc / screenshot_social / editorial / comparison_split / data_viz / meme) entre les concepts pour ne PAS empiler 5 visuels premium-cinematic. Sur Meta, le tout-cinematic perd contre la diversité, parce que l'audience scroll-fatigue les 'belles pubs'. Vise typiquement : 2 cinematic premium pour l'identité de marque + 1 ugc relatable + 1 screenshot social + 1 éditorial / data viz pour la crédibilité. Adapte selon l'angle du produit. Évite plus de 2 concepts dans le même render_style.",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          rationale: { type: "string" },
          render_style: {
            type: "string",
            enum: [
              "cinematic",
              "ugc",
              "screenshot_social",
              "editorial",
              "comparison_split",
              "data_viz",
              "meme",
            ],
            description:
              "cinematic = premium Apple-keynote (3D, Octane, hero shot). ugc = phone-shot iPhone, lumière naturelle, sujet humain casual. screenshot_social = faux SMS / DM / tweet / commentaire Insta — pas de photo. editorial = magazine finance Les Echos / Capital, serif, kicker, byline. comparison_split = diptyque avant/après, eux/nous, concurrence/produit. data_viz = chart-driven, la data est le héros (FT/Bloomberg style). meme = format meme reconnaissable avec punchline. La description doit refléter le style choisi.",
          },
          description: { type: "string" },
          comparison_labels: {
            type: "array",
            items: { type: "string" },
            minItems: 2,
            maxItems: 2,
            description:
              "REQUIS UNIQUEMENT si render_style=comparison_split. Tableau de 2 labels courts (1-3 mots, MAJUSCULES) pour étiqueter chaque moitié du diptyque. Exemples : ['AVANT','APRÈS'], ['VOTRE BANQUE','NOTRE OFFRE'], ['SANS X','AVEC X'], ['LIVRET A','[PRODUIT]']. Le 1er label = côté gauche / pain / statu-quo, le 2nd = côté droit / solution / produit.",
          },
        },
        required: ["name", "rationale", "render_style", "description"],
      },
    },
  },
  required: [
    "product_summary",
    "art_direction",
    "text_overlay",
    "angles",
    "concepts",
  ],
} as const;
